### ISSUE TITLE
Path issue running Index.html

### ISSUE THREAD

**Issue by chandu2366** [Go-LiveLabs/MEAN-Stack-Series-1---Node-and-Angular#1]
I started to encounter an issue with the path in the URL while running the index.html.  As I started working through the same, I was able to resolve it in the last 4) step .  I hope I am on the right track on editing the configuration.  

1)
when i run the web server . 
it showed that the server was listening on port 3000
and connected to mongo db

but when I launch the Index.html from the public folder and opens on chrome.
noticed is was http://localhost:63342/Intro-express/public/index.html
with a different port number.
 
Also noticed that there is an error for http://localhost:63342/contacts in the browser console.

In Webstorm, I tried to change preferences > build, Execution, Deployment > Debugger > port :63342 to 3000. but still had the same issue.

2)  
I manually changed the path  to http://localhost:3000/Intro-express/public/index.html in the browser and I got the following 404 error.

Error: Not Found
    at /Users/Chandu/WebstormProjects/Intro-express/app.js:37:13
    at Layer.handle [as handle_request] (/Users/Chandu/WebstormProjects/Intro-express/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/Chandu/WebstormProjects/Intro-express/node_modules/express/lib/router/index.js:312:13)

3) when I manually changed the URL as 
 http://localhost:3000/index.html,  It fetched the data correctly and displayed

4) Then finally was able to narrow down the issue and  changed the URL path under 'Edit Configuration' to  http://localhost:3000/index.html .   then it started working fine..

**Comment by pvtech** [comment]
You should use http://localhost:3000 to test. It will automatically render index.html

 - Your server was running on port 3000.  Hence, running on 63342, will not allow it to connect to the REST api, as your port is different. Check out [Same Origin Policy](https://en.wikipedia.org/wiki/Same-origin_policy)
 - localhost:3000 directly maps to the public folder, hence /public is not required. If you provide it, it searches for a public folder within the public folder.
 - http://localhost:3000 will do, index.html is not required
 - Just change the file to http://localhost:3000 and it will work the same (correct approach)

REST ful endpoints should not mention the representation a.k.a the file extension, in this case, index.html, hence I suggest using the http://localhost:3000 directly
